# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param n the parameter of the conditional distribution(binomal) of x
#' @param a the first parameter of the conditional distribution(beta) of y
#' @param b the second parameter of the conditional distribution(beta) of y
#' @return generated samples \code{mat}
#' @examples
#' \dontrun{
#'	a <- b <- 5;n <- 20;N <- 1000
#' gibR <- gibbsR(N, 10, n, a, b)
#' par(mfrow=c(2,1));
#' plot(gibR[,1],type='l')
#' plot(gibR[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin, n, a, b) {
    .Call('_StatComp21057_gibbsC', PACKAGE = 'StatComp21057', N, thin, n, a, b)
}

